{% set name = "triangle" %}
{% set version = "20200424" %}
{% set prefix = "py" %}

package:
  name: {{ prefix|lower }}-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc207641f8f39986f7d2bee1b91688a588cd235d2e67777422f94e61fece27e9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.24.0
  run:
    - numpy
    - python

test:
  imports:
    - triangle

about:
  home: https://rufat.be/triangle
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'python interface to tetgen, a powerful and fast mesh generator'
  description: |
     Triangle is a python wrapper around Jonathan Richard
     Shewchuk's two-dimensional quality mesh generator and
     delaunay triangulator library, available here. This
     implementation utilizes Cython to wrap the C API as closely
     as possible. The source is available on Github, and the
     documentation can be accessed at rufat.be/triangle.

  doc_url: https://rufat.be/triangle/
  dev_url: https://github.com/drufat/triangle

extra:
  recipe-maintainers:
       - Marcello-Sega
